export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL';

export const UNLOAD_DATA_REQUEST = 'UNLOAD_DATA_REQUEST';
export const UNLOAD_DATA_SUCCESS = 'UNLOAD_DATA_SUCCESS';
export const UNLOAD_DATA_FAIL = 'UNLOAD_DATA_FAIL';

export const UPDATE_SECONDS_REQUEST = 'UPDATE_SECONDS_REQUEST';
export const UPDATE_SECONDS_SUCCESS = 'UPDATE_SECONDS_SUCCESS';
export const UPDATE_SECONDS_FAIL = 'UPDATE_SECONDS_FAIL';